# Code to perform Low Rank Adaptation (LoRA) on the visiion encoders

In [1]:
import torch
import  torch.nn.functional as F 
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
import open_clip
import numpy as np
import pandas as pd
from tqdm import tqdm
import os
from sklearn.metrics import accuracy_score, classification_report, top_k_accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Optional, Callable

In [2]:
def evaluate(model,
            text_features : torch.Tensor,
            dl : DataLoader,
            num_classes : int,
            class_offsets,
            loss_func: Optional[Callable] = None,
            CM: Optional[torch.Tensor] = None,
            device : torch.device = torch.device('cpu')
            ):

#        text_features = text_features / torch.linalg.norm(text_features,dim=-1, keepdim=True)

    eval_loss = 0.0
    y_true, y_pred = [], []
    probs_collector = []
    model_dtype = next(model.parameters()).dtype
    running_loss = 0.0
    with torch.no_grad():
        for imgs, labels in dl:
            imgs = imgs.to(device, dtype=model_dtype)
            img_features = model.encode_image(imgs)
            img_features = img_features / torch.linalg.norm(img_features,dim=-1, keepdim=True)

            # native logit scale  * custom temperature
            logit_scale = model.logit_scale.exp() #* temp
            logits = logit_scale * (img_features @ text_features.T)

            # class prompt aggregation
            class_logits = []
            for i in range(num_classes):
                s, e = class_offsets[i], class_offsets[i+1]
                class_logits.append(logits[:, s:e].mean(dim=1))
            class_logits = torch.stack(class_logits, dim=1)

            if loss_func is not None and CM is not None:
                loss = loss_func(class_logits, labels.to(device), CM = CM.to(device) ) ###################### to finish            

            prob = class_logits.softmax(dim=-1)
            pred = prob.argmax(dim=-1)

            y_true.extend(labels.tolist())
            y_pred.extend(pred.tolist())
            probs_collector.append(prob.cpu().numpy())
            if loss_func is not None and CM is not None:
                running_loss += loss.item()
    
    if loss_func is not None and CM is not None:   
        eval_loss = running_loss / len(dl)

    y_true = np.array(y_true, dtype=int)
    y_pred = np.array(y_pred, dtype=int)
    probs = np.concatenate(probs_collector, axis=0)

    top1 = accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average="macro")
    top2 = top_k_accuracy_score(y_true, probs, k=min(2, num_classes), labels=np.arange(num_classes))
    top3 = top_k_accuracy_score(y_true, probs, k=min(3, num_classes), labels=np.arange(num_classes))

    return top1, macro_f1, top2, top3, y_true, y_pred, probs, eval_loss

In [3]:
# saves the per class performance in the file ./<CSV_PER_CLASS_FOLDER>/<model_name>.csv
# also saves the confusion matrix in a file ./<CONF_MATRIX_FOLDER>/<model_name
def save_performance_per_class(y_true,y_pred,model_name:str, classnames: list[str], CSV_PER_CLASS_FOLDER, CONF_MATRIX_FOLDER) -> torch.Tensor:
    df=pd.DataFrame(classification_report(y_true, y_pred, target_names=classnames, digits=4 , zero_division=0,output_dict=True))
    df=df.transpose()
    df.columns=["Precision","Recall","F1-score","Support"]
    df.to_csv(os.path.join(CSV_PER_CLASS_FOLDER, model_name+'.csv'), index=True)

    C = torch.from_numpy(confusion_matrix(y_true, y_pred, normalize='true'))
    fig, ax = plt.subplots(figsize=(8, 6))
    ConfusionMatrixDisplay.from_predictions(
        y_true, y_pred,
        display_labels=classnames,
        normalize="true",           # percentuali per riga
        cmap="Blues",
        include_values=False,       # evita numeri sopra le celle se hai tante classi
        xticks_rotation=90,
        ax=ax,
        colorbar=True
    )
    
    ax.set_title("Confusion Matrix (normalized)")
    plt.tight_layout()
    plt.savefig(os.path.join(CONF_MATRIX_FOLDER, model_name))
    plt.close()
    return C

In [4]:
def save_to_csv(row:dict, CSV_PATH):
    df = pd.DataFrame([row])
    display(df)

    # Aggiungi le performance al csv con tutti i modelli
    if os.path.exists(CSV_PATH):
        old = pd.read_csv(CSV_PATH)
        out = pd.concat([old, df], ignore_index=True)
    else:
        out = df.copy()
    out.to_csv(CSV_PATH, index=False)

In [5]:
# From https://github.com/MaxZanella/CLIP-LoRA/blob/main/loralib/layers.py
#  ------------------------------------------------------------------------------------------
#  This code is reconstructed based on loralib (https://github.com/microsoft/LoRA) by Baijiong Lin.
#  ------------------------------------------------------------------------------------------
import torch
import torch.nn as nn
import torch.nn.functional as F

import math
from typing import Optional, List

def set_param(curr_mod, name, param=None, mode='update'):
    r"""Refer to https://github.com/Baijiong-Lin/MOML/blob/main/MTL/utils.py"""
    if '.' in name:
        n = name.split('.')
        module_name = n[0]
        rest = '.'.join(n[1:])
        for name, mod in curr_mod.named_children():
            if module_name == name:
                return set_param(mod, rest, param, mode=mode)
    else:
        if mode == 'update':
            delattr(curr_mod, name)
            setattr(curr_mod, name, param)
        elif mode == 'get':
            if hasattr(curr_mod, name):
                p = getattr(curr_mod, name)
                return p

class LoRALayer():
    def __init__(
        self, 
        r: int, 
        lora_alpha: int, 
        fan_in_fan_out: bool = False,
        dropout_rate:float = 0,
    ):
        self.r = r
        self.lora_alpha = lora_alpha
        self.dropout_rate = dropout_rate
        if self.r > 0:
            #self.scaling = self.lora_alpha / self.r
            self.scaling = self.lora_alpha/math.sqrt(self.r) # 
        # Mark the weight as unmerged
        self.merged = False
        # Set this to True if the layer to replace stores weight like (fan_in, fan_out)
        self.fan_in_fan_out = fan_in_fan_out
        # define params that require LoRA {'param_name': 'lora_name'}
        self.params_with_lora = {}

    def register_lora_param(self):
        r"""Register LoRA matrix"""
        for param_name, lora_name in self.params_with_lora.items():
            assert len(eval(f'self.{param_name}').size()) == 2
            self.register_parameter(f'{lora_name}_lora_A', 
                nn.Parameter(eval(f'self.{param_name}').new_zeros((self.r, eval(f'self.{param_name}').size()[1])))
                )
            self.register_parameter(f'{lora_name}_lora_B', 
                nn.Parameter(eval(f'self.{param_name}').new_zeros((eval(f'self.{param_name}').size()[0], self.r)))
                )
                
            eval(f'self.{param_name}').requires_grad = False

    def init_lora_param(self):
        for param_name, lora_name in self.params_with_lora.items():
            if hasattr(self, f'{lora_name}_lora_A'):
                # initialize A the same way as the default for nn.Linear and B to zero
                nn.init.kaiming_uniform_(eval(f'self.{lora_name}_lora_A'), a=math.sqrt(5))
                nn.init.zeros_(eval(f'self.{lora_name}_lora_B'))

    def transpose(self, w: torch.Tensor):
        return w.transpose(0, 1) if self.fan_in_fan_out else w

    def merge_BA(self, param_name: str):
        lora_name = self.params_with_lora[param_name]
        return self.transpose((eval(f'self.{lora_name}_lora_B') @ eval(f'self.{lora_name}_lora_A')).view(eval(f'self.{param_name}').shape))

    
   
    
    def merge_lora_param(self):
        r"""p_new = p + scaling * B @ A and keep differentiable to A and B"""
        for param_name, lora_name in self.params_with_lora.items():
            p = set_param(self, param_name, mode='get')
            # detach() is very important here
            
            p_new = p.detach() + self.merge_BA(param_name) * self.scaling
            set_param(self, param_name, param=p_new, mode='update')

    def add_lora_data(self):
        r"""NOT differentiable"""
        for param_name, lora_name in self.params_with_lora.items():
            eval(f'self.{param_name}').data += self.merge_BA(param_name) * self.scaling
    
    def sub_lora_data(self):
        r"""NOT differentiable"""
        for param_name, lora_name in self.params_with_lora.items():
            eval(f'self.{param_name}').data -= self.merge_BA(param_name) * self.scaling
            
    
    def lora_train(self, mode: bool = True):
        if mode:
            if self.merged and self.r > 0:
            # Make sure that the weights are not merged
                self.sub_lora_data()
            self.merged = False
        else:
            if not self.merged and self.r > 0:
            # Merge the weights and mark it
                self.add_lora_data()
            self.merged = True 


class LinearLoRA(nn.Linear, LoRALayer):
    # LoRA implemented in a Linear layer
    def __init__(
        self, 
        existing_linear: nn.Linear,
        r: int = 0, 
        lora_alpha: int = 1, 
        fan_in_fan_out: bool = False,
        dropout_rate = 0.,
        **kwargs
    ):
        super().__init__(
            in_features=existing_linear.in_features, 
            out_features=existing_linear.out_features)
        
        self.load_state_dict(existing_linear.state_dict())
        LoRALayer.__init__(self, r=r, lora_alpha=lora_alpha, fan_in_fan_out=fan_in_fan_out)

        # Actual trainable parameters
        self.params_with_lora = {'weight': 'w'}
        if r > 0:
            self.register_lora_param()
        self.init_lora_param()
        self.weight.data = self.transpose(self.weight.data)
        if dropout_rate > 0:
            self.dropout = nn.Dropout(dropout_rate)
        else:
            self.dropout = None

    def train(self, mode: bool = True):
        super().train(mode)     
        self.lora_train(mode)

    def forward(self, x: torch.Tensor, **kwargs):
        # The original implementation had a bug/inefficiency here.
        # This corrected version is much more memory-friendly.

        # Compute the original linear transformation with frozen weights
        original_output = F.linear(x, self.transpose(self.weight), self.bias)

        # Compute and add the LoRA adjustment
        if self.r > 0 and not self.merged:
            
            # Apply dropout to the input if in training mode
            if self.training and self.dropout is not None:
                x_dropout = self.dropout(x)
            else:
                x_dropout = x

            # Get the LoRA matrices. Note: lora_A is already (r, in_features)
            lora_A = self.w_lora_A 
            lora_B = self.w_lora_B
            
            # Efficient computation: (x @ A.T) @ B.T
            # This keeps the intermediate matrix size small (batch_size, r)
            lora_adjustment = (x_dropout @ lora_A.transpose(0, 1)) @ lora_B.transpose(0, 1) * self.scaling
            
            result = original_output + lora_adjustment
        else:
            result = original_output
            
        return result
    # def forward(self, x: torch.Tensor, **kwargs):
        
    #     if self.dropout is None: # do as before
    #         if self.r > 0 and not self.merged:
    #             self.merge_lora_param()
    #             result = nn.Linear.forward(self, x, **kwargs)
    #             self.sub_lora_data()
    #             return result
    #         else:
    #             return nn.Linear.forward(self, x, **kwargs)
            
    #     # Compute the original linear transformation
    #     original_output = nn.Linear.forward(self, x)

    #     if self.training and self.dropout.p > 0:
    #         x = self.dropout(x)
        
    #     if self.r > 0 and not self.merged:
    #         lora_adjustment = torch.matmul(x,self.merge_BA('weight').transpose(0, 1)) * self.scaling 
    #         result = original_output + lora_adjustment
    #     else:
    #         result = original_output
    #     return result

In [6]:
def replace_linear_with_lora(model : torch.nn.Transformer, target_names: list[str], r: int=8, alpha: int=32, lora_dropout: float=0.1):
    for name, mod in model.named_modules():
        if any(target in name for target in target_names) and isinstance(mod, torch.nn.Linear):
            lora = LinearLoRA(mod, r, alpha, dropout_rate=lora_dropout)
            lora.train()
            # Need to use set_param or navigate the hierarchy to replace
            parent_name, child_name = name.rsplit('.', 1)
            parent = model
            for part in parent_name.split('.'):
                parent = getattr(parent, part)
            setattr(parent, child_name, lora)

In [7]:
def loss_weights_func(y : torch.Tensor) -> torch.Tensor:
    a = y.int().bincount()
    w = 1/a
    return w / w.mean()


class weighted_conf_mat_CELoss(torch.nn.Module):
        
    def __init__(self,weights: Optional[torch.Tensor] = None, beta : float =0.05):    
        super().__init__()
        self.W = weights
        self.beta = beta
        self.CE = torch.nn.CrossEntropyLoss(weight=self.W)

    def forward(self,logits: torch.Tensor, labels: torch.Tensor, CM: torch.Tensor ):
        if len(logits.shape) == 1:
            logits = logits.unsqueeze(dim=0)
            labels = labels.unsqueeze(dim=0)
        CM = CM.clone()
        CM[torch.arange(CM.shape[0]), torch.arange(CM.shape[0])] = 0
        logits -= self.beta * CM[labels] 
        return self.CE(logits, labels)

In [8]:
model_name = "ViT-L-14"
pretrained = "openai" 
LORA_MODEL_SAVE_PATH = "LoRA"
CSV_PATH = "LoRA_benchmark_results.csv"
CSV_PER_CLASS_FOLDER = "./LoRA_per_class_metrics/"
CONF_MATRIX_FOLDER="./LoRA_confusoin_matrices/"
EPOCHS = 30
BATCH_SIZE = 32
loss_beta = 0.4
TEMPLATES = [
    "a photo of {} architecture",
    "a photograph of {} architecture",
    "an image of {} architecture",
    "a picture of {} architecture",
    "a photo of the {} architectural style",
    "the {} architectural style",
    "a photo of a {} style building",
    "a {} style building",
    "a building in the {} style",
    "{}-style building",
    "a {} building",
    "a building of {} architecture",
    "a representation of {} architecture",
    "the facade of a {} building",
    "an example of {} architecture",
]
if not os.path.isdir(CSV_PER_CLASS_FOLDER):
    os.makedirs(CSV_PER_CLASS_FOLDER)
if not os.path.isdir(CONF_MATRIX_FOLDER):
    os.makedirs(CONF_MATRIX_FOLDER)

In [9]:
model, train_preprocess, test_preprocess = open_clip.create_model_and_transforms(model_name,pretrained)
print(model.visual)


device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

/home/simone/anaconda3/envs/CV/lib/python3.13/site-packages/open_clip/factory.py:450: UserWarning: QuickGELU mismatch between final model config (quick_gelu=False) and pretrained tag 'openai' (quick_gelu=True).
  warnings.warn(

VisionTransformer(
  (conv1): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
  (patch_dropout): Identity()
  (ln_pre): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
  (transformer): Transformer(
    (resblocks): ModuleList(
      (0-23): 24 x ResidualAttentionBlock(
        (ln_1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=1024, out_features=1024, bias=True)
        )
        (ls_1): Identity()
        (ln_2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (mlp): Sequential(
          (c_fc): Linear(in_features=1024, out_features=4096, bias=True)
          (gelu): GELU(approximate='none')
          (c_proj): Linear(in_features=4096, out_features=1024, bias=True)
        )
        (ls_2): Identity()
      )
    )
  )
  (ln_post): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
)

In [10]:

train_ds = ImageFolder("../../datasets/architectural-styles-dataset-spl-warp-lanczos/train",transform=train_preprocess) # type:ignore
train_dl = DataLoader(train_ds,batch_size=BATCH_SIZE, shuffle=True, num_workers=4, pin_memory=True )

eval_ds = ImageFolder("../../datasets/architectural-styles-dataset-spl-warp-lanczos/valid",transform=test_preprocess) # type:ignore
eval_dl = DataLoader(eval_ds,batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True )
classnames = train_ds.classes
num_classes = len(train_ds.classes)

### Compute text embeddings for all the prompts

In [11]:



all_prompts, class_offsets = [], [0]
for cname in classnames:
    ps = [t.format(cname) for t in TEMPLATES] + [f"{cname} architecture"]
    all_prompts.extend(ps)
    class_offsets.append(len(all_prompts))

tokenizer = open_clip.get_tokenizer(model_name)
tokens = tokenizer(all_prompts).to(device)
model.to(device)
with torch.no_grad():
    text_features = model.encode_text(tokens)  # type: ignore
    text_features = text_features / torch.linalg.norm(text_features,dim=-1, keepdim=True)


model.to(torch.device('cpu'))
torch.cuda.empty_cache()

In [ ]:
from torch import autocast, GradScaler

# 1. Freeze everything
for name, p in model.named_parameters():
    p.requires_grad = False

# 2. Inject LoRA (wrap selected Linear layers)
replace_linear_with_lora(model.visual.transformer, target_names=["out_proj", "c_fc", "c_proj"], r=4, alpha=8, lora_dropout=0.35) # type:ignore

# 3. Verify LoRA params are trainable
# for n, p in model.named_parameters():
#     if p.requires_grad:
#         print("Trainable:", n, p.shape)  # should print only lora_A/lora_B (and maybe logit_scale if you unfreeze it)

# --- Model & setup ---

text_features = text_features.to(device)
model.visual = model.visual.to(device)
# Wrap the whole model for multi-GPU (before optimizer creation)
#model.visual = torch.nn.DataParallel(model.visual)

torch.cuda.synchronize()

loss_func = weighted_conf_mat_CELoss(
    weights=loss_weights_func(torch.Tensor(train_ds.targets)).to(device),
    beta=loss_beta
)

optimizer = torch.optim.Adam(
    [p for p in model.parameters() if p.requires_grad],
    lr=0.0005
)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=EPOCHS-10
)

scaler = GradScaler()   # <-- For AMP
model_dtype = next(model.parameters()).dtype
model.train()

train_loss = 0.0
pbar = tqdm(range(EPOCHS))
CM = torch.zeros((num_classes, num_classes))
logit_scale = model.logit_scale.exp()
max_top1 = 0
# --- Training loop ---
for e in pbar:
    # ----- Evaluation -----
    model.eval()
    top1, macro_f1, top2, top3, eval_y_true, eval_y_pred, probs, eval_loss = evaluate(
        model, text_features, eval_dl, num_classes, class_offsets, loss_func, CM, device
    )

    row = {
        "Timestamp": datetime.now(ZoneInfo("Europe/Rome")).isoformat(),
        "Model": model_name,
        "Pretrained": pretrained,
        "Scenario": "LoRA",
        "loss beta": loss_beta,
        " epoch": f"{e}/{EPOCHS}",
        "train loss": train_loss,
        "eval loss": eval_loss,
        "Top-1 Acc": round(float(top1), 4),
        "Top-2 Acc": round(float(top2), 4),
        "Top-3 Acc": round(float(top3), 4),
        "Macro-F1": round(float(macro_f1), 4),
        "Batch size": int(BATCH_SIZE)
    }
    save_to_csv(row, CSV_PATH)
    CM = save_performance_per_class(
        eval_y_true, eval_y_pred, model_name, classnames,
        CSV_PER_CLASS_FOLDER, CONF_MATRIX_FOLDER
    )
    if top1 > max_top1:
        torch.save(model.state_dict(), LORA_MODEL_SAVE_PATH+"_best.pt")
        max_top1 = top1
    # ----- Training -----
    model.train()
    CM = CM.to(device)
    running_loss = 0.0
    torch.cuda.empty_cache()
    optimizer.zero_grad()

    global_imgs, global_labels = [], []

    for i, (imgs, labels) in enumerate(train_dl):
        imgs = imgs.to(device, dtype=model_dtype, non_blocking=True)
        labels = labels.to(device, non_blocking=True)
        pbar.set_description(
        f"Eval Accuracy: {top1:.4f}  Eval Loss: {eval_loss:.4f}  Train Loss: {train_loss:.4f} . Batch:{i}/{len(train_dl)}"
        )
        # --- AMP forward pass ---
        #with autocast(device_type="cuda", dtype=torch.float16):
        img_features = model.visual(imgs)  # use .module for DataParallel
        img_features = img_features / torch.linalg.norm(img_features, dim=-1, keepdim=True)
        logits = logit_scale * (img_features @ text_features.T)

        # class-level aggregation
        class_logits = []
        for j in range(num_classes):
            s, e = class_offsets[j], class_offsets[j + 1]
            class_logits.append(logits[:, s:e].mean(dim=1))
        class_logits = torch.stack(class_logits, dim=1).to(device)

        loss = loss_func(class_logits, labels, CM=CM)

        # --- Backward (scaled) ---
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()
        optimizer.zero_grad(set_to_none=True)
        running_loss += loss.item()

    train_loss = running_loss / len(train_dl)
    CM = CM.to("cpu")
    torch.save(model.state_dict(), LORA_MODEL_SAVE_PATH+"_checkpoint.pt")

# --- Final evaluation & save ---
model.eval()
top1, macro_f1, top2, top3, eval_y_true, eval_y_pred, probs, eval_loss = evaluate(
    model, text_features, eval_dl, num_classes, class_offsets, loss_func, CM, device
)
row = {
    "Timestamp": datetime.now(ZoneInfo("Europe/Rome")).isoformat(),
    "Model": model_name,
    "Pretrained": pretrained,
    "Scenario": "LoRA",
    "loss beta": loss_beta,
    " epoch": f"{e}/{EPOCHS}",
    "Top-1 Acc": round(float(top1), 4),
    "Top-2 Acc": round(float(top2), 4),
    "Top-3 Acc": round(float(top3), 4),
    "Macro-F1": round(float(macro_f1), 4),
    "Batch size": int(BATCH_SIZE)
}
save_to_csv(row, CSV_PATH)
CM = save_performance_per_class(
    eval_y_true, eval_y_pred, model_name, classnames,
    CSV_PER_CLASS_FOLDER, CONF_MATRIX_FOLDER
)
pbar.set_description(
    f"Eval Accuracy: {top1:.4f}  Eval Loss: {eval_loss:.4f}  Train Loss: {train_loss:.4f}"
)
if top1 > max_top1:
    torch.save(model.state_dict(), LORA_MODEL_SAVE_PATH+"_best.pt")
    max_top1 = top1
# Save LoRA weights (unwrapped from DataParallel)

  0%|          | 0/30 [00:00<?, ?it/s]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:25:16.015319+01:00,ViT-L-14,openai,LoRA,0.4,0/30,0.0,1.395736,0.5804,0.7333,0.8112,0.5618,32

Eval Accuracy: 0.5804  Eval Loss: 1.3957  Train Loss: 0.0000 . Batch:226/227:   3%|▎         | 1/30 [04:59<2:24:51, 299.69s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:30:16.519627+01:00,ViT-L-14,openai,LoRA,0.4,1/30,0.790547,0.615141,0.8112,0.9109,0.9509,0.811,32

Eval Accuracy: 0.8112  Eval Loss: 0.6151  Train Loss: 0.7905 . Batch:226/227:   7%|▋         | 2/30 [10:03<2:21:04, 302.30s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:35:20.624219+01:00,ViT-L-14,openai,LoRA,0.4,2/30,0.455201,0.572334,0.8175,0.9305,0.9579,0.8173,32

Eval Accuracy: 0.8175  Eval Loss: 0.5723  Train Loss: 0.4552 . Batch:226/227:  10%|█         | 3/30 [15:07<2:16:25, 303.15s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:40:24.800737+01:00,ViT-L-14,openai,LoRA,0.4,3/30,0.285496,0.636705,0.8084,0.9193,0.9551,0.8088,32

Eval Accuracy: 0.8084  Eval Loss: 0.6367  Train Loss: 0.2855 . Batch:226/227:  13%|█▎        | 4/30 [20:10<2:11:15, 302.91s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:45:27.314281+01:00,ViT-L-14,openai,LoRA,0.4,4/30,0.202638,0.61579,0.8225,0.9256,0.9558,0.8226,32

Eval Accuracy: 0.8225  Eval Loss: 0.6158  Train Loss: 0.2026 . Batch:226/227:  17%|█▋        | 5/30 [25:15<2:06:26, 303.48s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:50:31.876835+01:00,ViT-L-14,openai,LoRA,0.4,5/30,0.155111,0.648228,0.8232,0.9172,0.9572,0.8229,32

Eval Accuracy: 0.8232  Eval Loss: 0.6482  Train Loss: 0.1551 . Batch:226/227:  20%|██        | 6/30 [30:19<2:01:29, 303.72s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T17:55:36.005434+01:00,ViT-L-14,openai,LoRA,0.4,6/30,0.143558,0.665139,0.8211,0.9242,0.9579,0.8203,32

Eval Accuracy: 0.8211  Eval Loss: 0.6651  Train Loss: 0.1436 . Batch:226/227:  23%|██▎       | 7/30 [35:21<1:56:15, 303.29s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:00:38.406707+01:00,ViT-L-14,openai,LoRA,0.4,7/30,0.102822,0.720849,0.814,0.9221,0.96,0.8128,32

Eval Accuracy: 0.8140  Eval Loss: 0.7208  Train Loss: 0.1028 . Batch:226/227:  27%|██▋       | 8/30 [40:24<1:51:06, 303.03s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:05:40.890745+01:00,ViT-L-14,openai,LoRA,0.4,8/30,0.096901,0.703852,0.814,0.9242,0.9537,0.814,32

Eval Accuracy: 0.8140  Eval Loss: 0.7039  Train Loss: 0.0969 . Batch:226/227:  30%|███       | 9/30 [45:26<1:46:01, 302.93s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:10:43.612167+01:00,ViT-L-14,openai,LoRA,0.4,9/30,0.171644,0.792642,0.8,0.9144,0.9516,0.7985,32

Eval Accuracy: 0.8000  Eval Loss: 0.7926  Train Loss: 0.1716 . Batch:226/227:  33%|███▎      | 10/30 [50:29<1:40:57, 302.88s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:15:46.378286+01:00,ViT-L-14,openai,LoRA,0.4,10/30,0.180314,0.645257,0.8189,0.9235,0.953,0.8179,32

Eval Accuracy: 0.8189  Eval Loss: 0.6453  Train Loss: 0.1803 . Batch:226/227:  37%|███▋      | 11/30 [55:32<1:35:54, 302.85s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:20:49.198041+01:00,ViT-L-14,openai,LoRA,0.4,11/30,0.11088,0.693986,0.8154,0.9277,0.9565,0.816,32

Eval Accuracy: 0.8154  Eval Loss: 0.6940  Train Loss: 0.1109 . Batch:226/227:  40%|████      | 12/30 [1:00:35<1:30:52, 302.90s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:25:52.207912+01:00,ViT-L-14,openai,LoRA,0.4,12/30,0.121864,0.803141,0.8056,0.8989,0.9474,0.8045,32

Eval Accuracy: 0.8056  Eval Loss: 0.8031  Train Loss: 0.1219 . Batch:226/227:  43%|████▎     | 13/30 [1:05:38<1:25:50, 302.96s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:30:55.309765+01:00,ViT-L-14,openai,LoRA,0.4,13/30,0.095563,0.708959,0.8246,0.9228,0.9572,0.8242,32

Eval Accuracy: 0.8246  Eval Loss: 0.7090  Train Loss: 0.0956 . Batch:226/227:  47%|████▋     | 14/30 [1:10:43<1:20:55, 303.49s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:36:00.018619+01:00,ViT-L-14,openai,LoRA,0.4,14/30,0.067718,0.772712,0.8288,0.9116,0.9544,0.8289,32

Eval Accuracy: 0.8288  Eval Loss: 0.7727  Train Loss: 0.0677 . Batch:226/227:  50%|█████     | 15/30 [1:15:47<1:15:57, 303.86s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:41:04.703657+01:00,ViT-L-14,openai,LoRA,0.4,15/30,0.087979,0.811239,0.8105,0.9046,0.9544,0.8106,32

Eval Accuracy: 0.8105  Eval Loss: 0.8112  Train Loss: 0.0880 . Batch:226/227:  53%|█████▎    | 16/30 [1:20:51<1:10:50, 303.64s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:46:07.808412+01:00,ViT-L-14,openai,LoRA,0.4,16/30,0.107483,0.89067,0.7951,0.9081,0.9425,0.7955,32

Eval Accuracy: 0.7951  Eval Loss: 0.8907  Train Loss: 0.1075 . Batch:226/227:  57%|█████▋    | 17/30 [1:25:52<1:05:39, 303.02s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:51:08.876263+01:00,ViT-L-14,openai,LoRA,0.4,17/30,0.112703,0.798274,0.8126,0.9165,0.9572,0.8132,32

Eval Accuracy: 0.8126  Eval Loss: 0.7983  Train Loss: 0.1127 . Batch:226/227:  60%|██████    | 18/30 [1:30:48<1:00:12, 301.01s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T18:56:04.768274+01:00,ViT-L-14,openai,LoRA,0.4,18/30,0.081973,0.844373,0.8014,0.9088,0.9495,0.8033,32

Eval Accuracy: 0.8014  Eval Loss: 0.8444  Train Loss: 0.0820 . Batch:226/227:  63%|██████▎   | 19/30 [1:35:38<54:33, 297.63s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:00:54.884371+01:00,ViT-L-14,openai,LoRA,0.4,19/30,0.110538,0.785422,0.8161,0.9207,0.9565,0.8158,32

Eval Accuracy: 0.8161  Eval Loss: 0.7854  Train Loss: 0.1105 . Batch:226/227:  67%|██████▋   | 20/30 [1:40:33<49:27, 296.76s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:05:49.442712+01:00,ViT-L-14,openai,LoRA,0.4,20/30,0.0707,0.808241,0.807,0.9186,0.9432,0.8063,32

Eval Accuracy: 0.8070  Eval Loss: 0.8082  Train Loss: 0.0707 . Batch:226/227:  70%|███████   | 21/30 [1:45:24<44:16, 295.17s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:10:41.073085+01:00,ViT-L-14,openai,LoRA,0.4,21/30,0.059685,0.830002,0.8211,0.9165,0.9551,0.8209,32

Eval Accuracy: 0.8211  Eval Loss: 0.8300  Train Loss: 0.0597 . Batch:226/227:  73%|███████▎  | 22/30 [1:51:00<40:58, 307.32s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:16:20.197155+01:00,ViT-L-14,openai,LoRA,0.4,22/30,0.052824,0.766549,0.8309,0.9291,0.9537,0.8309,32

Eval Accuracy: 0.8309  Eval Loss: 0.7665  Train Loss: 0.0528 . Batch:226/227:  77%|███████▋  | 23/30 [1:56:45<37:09, 318.54s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:22:04.898399+01:00,ViT-L-14,openai,LoRA,0.4,23/30,0.092684,0.796433,0.8126,0.906,0.9432,0.8115,32

Eval Accuracy: 0.8126  Eval Loss: 0.7964  Train Loss: 0.0927 . Batch:226/227:  80%|████████  | 24/30 [2:02:27<32:34, 325.72s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:27:47.314726+01:00,ViT-L-14,openai,LoRA,0.4,24/30,0.159716,0.862441,0.7993,0.9074,0.9411,0.7972,32

Eval Accuracy: 0.7993  Eval Loss: 0.8624  Train Loss: 0.1597 . Batch:226/227:  83%|████████▎ | 25/30 [2:08:09<27:32, 330.54s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:33:29.173952+01:00,ViT-L-14,openai,LoRA,0.4,25/30,0.092581,0.857978,0.8133,0.9144,0.9523,0.812,32

Eval Accuracy: 0.8133  Eval Loss: 0.8580  Train Loss: 0.0926 . Batch:226/227:  87%|████████▋ | 26/30 [2:13:56<22:21, 335.42s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:39:16.531715+01:00,ViT-L-14,openai,LoRA,0.4,26/30,0.067417,0.828284,0.8196,0.9116,0.9502,0.8186,32

Eval Accuracy: 0.8196  Eval Loss: 0.8283  Train Loss: 0.0674 . Batch:226/227:  90%|█████████ | 27/30 [2:19:26<16:41, 333.77s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:44:45.282094+01:00,ViT-L-14,openai,LoRA,0.4,27/30,0.037381,0.888333,0.8042,0.9046,0.9453,0.8011,32

Eval Accuracy: 0.8042  Eval Loss: 0.8883  Train Loss: 0.0374 . Batch:226/227:  93%|█████████▎| 28/30 [2:24:52<11:02, 331.40s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:50:11.081362+01:00,ViT-L-14,openai,LoRA,0.4,28/30,0.036234,0.884929,0.8182,0.9165,0.9586,0.8177,32

Eval Accuracy: 0.8182  Eval Loss: 0.8849  Train Loss: 0.0362 . Batch:226/227:  97%|█████████▋| 29/30 [2:30:17<05:29, 329.72s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,train loss,eval loss,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T19:55:36.900867+01:00,ViT-L-14,openai,LoRA,0.4,29/30,0.04629,0.874994,0.8098,0.9102,0.9474,0.8094,32

Eval Accuracy: 0.8098  Eval Loss: 0.8750  Train Loss: 0.0463 . Batch:226/227: 100%|██████████| 30/30 [2:35:43<00:00, 311.46s/it]

,Timestamp,Model,Pretrained,Scenario,loss beta,epoch,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Batch size
0,2025-10-27T20:01:02.878665+01:00,ViT-L-14,openai,LoRA,0.4,400/30,0.7726,0.8919,0.934,0.7708,32