## Compare Zero-Shot Accuracy of Different models

This script is used to compare a list of different CLIP models in zero-shot classification.

### Comparison

At the end you will have a .csv file containing all the models names, the Top-1 and Top-2 Accuracies and the time to process an image to measure computation efficiency in ms/image.

In [11]:

# === Imports & Config ===
import os, time, json, math
from datetime import datetime
from zoneinfo import ZoneInfo
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
import open_clip
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, classification_report, top_k_accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import warnings
import gc

In [12]:
open_clip.list_pretrained()

[('RN50', 'openai'),
 ('RN50', 'yfcc15m'),
 ('RN50', 'cc12m'),
 ('RN101', 'openai'),
 ('RN101', 'yfcc15m'),
 ('RN50x4', 'openai'),
 ('RN50x16', 'openai'),
 ('RN50x64', 'openai'),
 ('ViT-B-32', 'openai'),
 ('ViT-B-32', 'laion400m_e31'),
 ('ViT-B-32', 'laion400m_e32'),
 ('ViT-B-32', 'laion2b_e16'),
 ('ViT-B-32', 'laion2b_s34b_b79k'),
 ('ViT-B-32', 'datacomp_xl_s13b_b90k'),
 ('ViT-B-32', 'datacomp_m_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_clip_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_laion_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_image_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_text_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_basic_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_s128m_b4k'),
 ('ViT-B-32', 'datacomp_s_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_clip_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_laion_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_image_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_text_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_basic_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_s13m_b4k'),
 ('ViT-B-32', 'metaclip_400m'),
 ('ViT-B-32', 'metaclip_fullcc'),
 ('ViT-B-32-256', 'datacomp_s34b_b86k'),
 ('ViT-B-16', 'openai'),
 ('ViT-B-16', 'laion400m_e31'),
 ('ViT-B-16', 'laion400m_e32'),
 ('ViT-B-16', 'laion2b_s34b_b88k'),
 ('ViT-B-16', 'datacomp_xl_s13b_b90k'),
 ('ViT-B-16', 'datacomp_l_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_clip_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_laion_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_image_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_text_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_basic_s1b_b8k'),
 ('ViT-B-16', 'commonpool_l_s1b_b8k'),
 ('ViT-B-16', 'dfn2b'),
 ('ViT-B-16', 'metaclip_400m'),
 ('ViT-B-16', 'metaclip_fullcc'),
 ('ViT-B-16-plus-240', 'laion400m_e31'),
 ('ViT-B-16-plus-240', 'laion400m_e32'),
 ('ViT-L-14', 'openai'),
 ('ViT-L-14', 'laion400m_e31'),
 ('ViT-L-14', 'laion400m_e32'),
 ('ViT-L-14', 'laion2b_s32b_b82k'),
 ('ViT-L-14', 'datacomp_xl_s13b_b90k'),
 ('ViT-L-14', 'commonpool_xl_clip_s13b_b90k'),
 ('ViT-L-14', 'commonpool_xl_laion_s13b_b90k'),
 ('ViT-L-14', 'commonpool_xl_s13b_b90k'),
 ('ViT-L-14', 'metaclip_400m'),
 ('ViT-L-14', 'metaclip_fullcc'),
 ('ViT-L-14', 'dfn2b'),
 ('ViT-L-14', 'dfn2b_s39b'),
 ('ViT-L-14-336', 'openai'),
 ('ViT-H-14', 'laion2b_s32b_b79k'),
 ('ViT-H-14', 'metaclip_fullcc'),
 ('ViT-H-14', 'metaclip_altogether'),
 ('ViT-H-14', 'dfn5b'),
 ('ViT-H-14-378', 'dfn5b'),
 ('ViT-g-14', 'laion2b_s12b_b42k'),
 ('ViT-g-14', 'laion2b_s34b_b88k'),
 ('ViT-bigG-14', 'laion2b_s39b_b160k'),
 ('ViT-bigG-14', 'metaclip_fullcc'),
 ('roberta-ViT-B-32', 'laion2b_s12b_b32k'),
 ('xlm-roberta-base-ViT-B-32', 'laion5b_s13b_b90k'),
 ('xlm-roberta-large-ViT-H-14', 'frozen_laion5b_s13b_b90k'),
 ('convnext_base', 'laion400m_s13b_b51k'),
 ('convnext_base_w', 'laion2b_s13b_b82k'),
 ('convnext_base_w', 'laion2b_s13b_b82k_augreg'),
 ('convnext_base_w', 'laion_aesthetic_s13b_b82k'),
 ('convnext_base_w_320', 'laion_aesthetic_s13b_b82k'),
 ('convnext_base_w_320', 'laion_aesthetic_s13b_b82k_augreg'),
 ('convnext_large_d', 'laion2b_s26b_b102k_augreg'),
 ('convnext_large_d_320', 'laion2b_s29b_b131k_ft'),
 ('convnext_large_d_320', 'laion2b_s29b_b131k_ft_soup'),
 ('convnext_xxlarge', 'laion2b_s34b_b82k_augreg'),
 ('convnext_xxlarge', 'laion2b_s34b_b82k_augreg_rewind'),
 ('convnext_xxlarge', 'laion2b_s34b_b82k_augreg_soup'),
 ('coca_ViT-B-32', 'laion2b_s13b_b90k'),
 ('coca_ViT-B-32', 'mscoco_finetuned_laion2b_s13b_b90k'),
 ('coca_ViT-L-14', 'laion2b_s13b_b90k'),
 ('coca_ViT-L-14', 'mscoco_finetuned_laion2b_s13b_b90k'),
 ('EVA01-g-14', 'laion400m_s11b_b41k'),
 ('EVA01-g-14-plus', 'merged2b_s11b_b114k'),
 ('EVA02-B-16', 'merged2b_s8b_b131k'),
 ('EVA02-L-14', 'merged2b_s4b_b131k'),
 ('EVA02-L-14-336', 'merged2b_s6b_b61k'),
 ('EVA02-E-14', 'laion2b_s4b_b115k'),
 ('EVA02-E-14-plus', 'laion2b_s9b_b144k'),
 ('ViT-B-16-SigLIP', 'webli'),
 ('ViT-B-16-SigLIP-256', 'webli'),
 ('ViT-B-16-SigLIP-i18n-256', 'webli'),
 ('ViT-B-16-SigLIP-384', 'webli'),
 ('ViT-B-16-SigLIP-512', 'webli'),
 ('ViT-L-16-SigLIP-256', 'webli'),
 ('ViT-L-16-SigLIP-384', 'webli'),
 ('ViT-SO400M-14-SigLIP', 'webli'),
 ('ViT-SO400M-16-SigLIP-i18n-256', 'webli'),
 ('ViT-SO400M-14-SigLIP-378', 'webli'),
 ('ViT-SO400M-14-SigLIP-384', 'webli'),
 ('ViT-B-32-SigLIP2-256', 'webli'),
 ('ViT-B-16-SigLIP2', 'webli'),
 ('ViT-B-16-SigLIP2-256', 'webli'),
 ('ViT-B-16-SigLIP2-384', 'webli'),
 ('ViT-B-16-SigLIP2-512', 'webli'),
 ('ViT-L-16-SigLIP2-256', 'webli'),
 ('ViT-L-16-SigLIP2-384', 'webli'),
 ('ViT-L-16-SigLIP2-512', 'webli'),
 ('ViT-SO400M-14-SigLIP2', 'webli'),
 ('ViT-SO400M-14-SigLIP2-378', 'webli'),
 ('ViT-SO400M-16-SigLIP2-256', 'webli'),
 ('ViT-SO400M-16-SigLIP2-384', 'webli'),
 ('ViT-SO400M-16-SigLIP2-512', 'webli'),
 ('ViT-gopt-16-SigLIP2-256', 'webli'),
 ('ViT-gopt-16-SigLIP2-384', 'webli'),
 ('ViT-L-14-CLIPA', 'datacomp1b'),
 ('ViT-L-14-CLIPA-336', 'datacomp1b'),
 ('ViT-H-14-CLIPA', 'datacomp1b'),
 ('ViT-H-14-CLIPA-336', 'laion2b'),
 ('ViT-H-14-CLIPA-336', 'datacomp1b'),
 ('ViT-bigG-14-CLIPA', 'datacomp1b'),
 ('ViT-bigG-14-CLIPA-336', 'datacomp1b'),
 ('nllb-clip-base', 'v1'),
 ('nllb-clip-large', 'v1'),
 ('nllb-clip-base-siglip', 'v1'),
 ('nllb-clip-base-siglip', 'mrl'),
 ('nllb-clip-large-siglip', 'v1'),
 ('nllb-clip-large-siglip', 'mrl'),
 ('MobileCLIP-S1', 'datacompdr'),
 ('MobileCLIP-S2', 'datacompdr'),
 ('MobileCLIP-B', 'datacompdr'),
 ('MobileCLIP-B', 'datacompdr_lt'),
 ('ViTamin-S', 'datacomp1b'),
 ('ViTamin-S-LTT', 'datacomp1b'),
 ('ViTamin-B', 'datacomp1b'),
 ('ViTamin-B-LTT', 'datacomp1b'),
 ('ViTamin-L', 'datacomp1b'),
 ('ViTamin-L-256', 'datacomp1b'),
 ('ViTamin-L-336', 'datacomp1b'),
 ('ViTamin-L-384', 'datacomp1b'),
 ('ViTamin-L2', 'datacomp1b'),
 ('ViTamin-L2-256', 'datacomp1b'),
 ('ViTamin-L2-336', 'datacomp1b'),
 ('ViTamin-L2-384', 'datacomp1b'),
 ('ViTamin-XL-256', 'datacomp1b'),
 ('ViTamin-XL-336', 'datacomp1b'),
 ('ViTamin-XL-384', 'datacomp1b'),
 ('PE-Core-T-16-384', 'meta'),
 ('PE-Core-S-16-384', 'meta'),
 ('PE-Core-B-16', 'meta'),
 ('PE-Core-L-14-336', 'meta'),
 ('PE-Core-bigG-14-448', 'meta'),
 ('ViT-L-14-worldwide', 'metaclip2_worldwide'),
 ('ViT-H-14-worldwide', 'metaclip2_worldwide'),
 ('ViT-H-14-worldwide-378', 'metaclip2_worldwide'),
 ('ViT-bigG-14-worldwide', 'metaclip2_worldwide'),
 ('ViT-bigG-14-worldwide-378', 'metaclip2_worldwide'),
 ('RN50-quickgelu', 'openai'),
 ('RN50-quickgelu', 'yfcc15m'),
 ('RN50-quickgelu', 'cc12m'),
 ('RN101-quickgelu', 'openai'),
 ('RN101-quickgelu', 'yfcc15m'),
 ('RN50x4-quickgelu', 'openai'),
 ('RN50x16-quickgelu', 'openai'),
 ('RN50x64-quickgelu', 'openai'),
 ('ViT-B-32-quickgelu', 'openai'),
 ('ViT-B-32-quickgelu', 'laion400m_e31'),
 ('ViT-B-32-quickgelu', 'laion400m_e32'),
 ('ViT-B-32-quickgelu', 'metaclip_400m'),
 ('ViT-B-32-quickgelu', 'metaclip_fullcc'),
 ('ViT-B-16-quickgelu', 'openai'),
 ('ViT-B-16-quickgelu', 'dfn2b'),
 ('ViT-B-16-quickgelu', 'metaclip_400m'),
 ('ViT-B-16-quickgelu', 'metaclip_fullcc'),
 ('ViT-L-14-quickgelu', 'openai'),
 ('ViT-L-14-quickgelu', 'metaclip_400m'),
 ('ViT-L-14-quickgelu', 'metaclip_fullcc'),
 ('ViT-L-14-quickgelu', 'dfn2b'),
 ('ViT-L-14-336-quickgelu', 'openai'),
 ('ViT-H-14-quickgelu', 'metaclip_fullcc'),
 ('ViT-H-14-quickgelu', 'dfn5b'),
 ('ViT-H-14-378-quickgelu', 'dfn5b'),
 ('ViT-bigG-14-quickgelu', 'metaclip_fullcc'),
 ('ViT-L-14-worldwide-quickgelu', 'metaclip2_worldwide'),
 ('ViT-H-14-worldwide-quickgelu', 'metaclip2_worldwide')]

In [13]:
MODELS_LIST=selected_models = [
    # --- OpenAI Baselines ---
    ('RN50', 'openai'),
    ('RN101', 'openai'),
    ('RN50x64', 'openai'),
    ('ViT-B-32', 'openai'),
    ('ViT-B-16', 'openai'),
    ('ViT-L-14', 'openai'),
    ('ViT-L-14-336', 'openai'),

    # --- LAION / DataComp ---
    ('ViT-B-32', 'laion2b_s34b_b79k'),
    ('ViT-B-16', 'laion2b_s34b_b88k'),
    ('ViT-L-14', 'laion2b_s32b_b82k'),
    ('ViT-H-14', 'laion2b_s32b_b79k'),
    ('ViT-g-14', 'laion2b_s12b_b42k'),
    ('ViT-bigG-14', 'laion2b_s39b_b160k'),
    ('ViT-B-32', 'datacomp_xl_s13b_b90k'),
    ('ViT-B-16', 'datacomp_xl_s13b_b90k'),
    ('ViT-L-14', 'datacomp_xl_s13b_b90k'),
    ('ViT-H-14', 'dfn5b'),

    # --- MetaCLIP ---
    ('ViT-B-32', 'metaclip_400m'),
    ('ViT-B-32', 'metaclip_fullcc'),
    ('ViT-L-14', 'metaclip_400m'),
    ('ViT-L-14', 'metaclip_fullcc'),
    ('ViT-H-14', 'metaclip_fullcc'),
    ('ViT-bigG-14', 'metaclip_fullcc'),

    # --- SigLIP (Google) ---
    ('ViT-B-16-SigLIP', 'webli'),
    ('ViT-B-16-SigLIP-256', 'webli'),
    ('ViT-B-16-SigLIP-384', 'webli'),
    ('ViT-B-16-SigLIP-512', 'webli'),
    ('ViT-L-16-SigLIP-256', 'webli'),
    ('ViT-L-16-SigLIP-384', 'webli'),
    ('ViT-SO400M-14-SigLIP-384', 'webli'),
    ('ViT-SO400M-14-SigLIP-378', 'webli'),

    # --- SigLIP2 ---
    ('ViT-B-16-SigLIP2', 'webli'),
    ('ViT-B-16-SigLIP2-256', 'webli'),
    ('ViT-B-16-SigLIP2-384', 'webli'),
    ('ViT-B-16-SigLIP2-512', 'webli'),
    ('ViT-L-16-SigLIP2-256', 'webli'),
    ('ViT-L-16-SigLIP2-384', 'webli'),
    ('ViT-L-16-SigLIP2-512', 'webli'),
    ('ViT-SO400M-14-SigLIP2', 'webli'),
    ('ViT-SO400M-14-SigLIP2-378', 'webli'),
    ('ViT-SO400M-16-SigLIP2-384', 'webli'),
    ('ViT-SO400M-16-SigLIP2-512', 'webli'),
    ('ViT-gopt-16-SigLIP2-384', 'webli'),

    # --- EVA ---
    ('EVA01-g-14', 'laion400m_s11b_b41k'),
    ('EVA02-B-16', 'merged2b_s8b_b131k'),
    ('EVA02-L-14', 'merged2b_s4b_b131k'),
    ('EVA02-L-14-336', 'merged2b_s6b_b61k'),
    ('EVA02-E-14', 'laion2b_s4b_b115k'),
    ('EVA02-E-14-plus', 'laion2b_s9b_b144k'),

    # --- ConvNeXt ---
    ('convnext_base', 'laion400m_s13b_b51k'),
    ('convnext_base_w', 'laion2b_s13b_b82k'),
    ('convnext_large_d', 'laion2b_s26b_b102k_augreg'),
    ('convnext_large_d_320', 'laion2b_s29b_b131k_ft_soup'),
    ('convnext_xxlarge', 'laion2b_s34b_b82k_augreg'),

    # --- CoCa ---
    ('coca_ViT-B-32', 'laion2b_s13b_b90k'),
    ('coca_ViT-L-14', 'laion2b_s13b_b90k'),

    # --- CLIPA ---
    ('ViT-L-14-CLIPA', 'datacomp1b'),
    ('ViT-L-14-CLIPA-336', 'datacomp1b'),
    ('ViT-H-14-CLIPA', 'datacomp1b'),
    ('ViT-H-14-CLIPA-336', 'datacomp1b'),
    ('ViT-bigG-14-CLIPA', 'datacomp1b'),

    # --- ViTamin ---
    ('ViTamin-L', 'datacomp1b'),
    ('ViTamin-L-336', 'datacomp1b'),
    ('ViTamin-L2', 'datacomp1b'),
    ('ViTamin-L2-384', 'datacomp1b'),
    ('ViTamin-XL-336', 'datacomp1b'),
    ('ViTamin-XL-384', 'datacomp1b'),

    # --- PE-Core (SOTA) ---
    ('PE-Core-B-16', 'meta'),
    ('PE-Core-L-14-336', 'meta'),
    ('PE-Core-bigG-14-448', 'meta'),

    # --- Worldwide (MetaCLIP2) ---
    ('ViT-H-14-worldwide-378', 'metaclip2_worldwide'),
    ('ViT-bigG-14-worldwide', 'metaclip2_worldwide'),
    ('ViT-bigG-14-worldwide-378', 'metaclip2_worldwide'),
]

In [ ]:
DATASET_PATH="../datasets/architectural-styles-dataset-spl-warp-lanczos"
SEED = 42
SPLIT="train"
BATCH_SIZE = 64
TEMPLATES = [
    "a photo of a {}"
    # "a photograph of {} architecture",
    # "an image of {} architecture",
    # "a picture of {} architecture",
    # "a photo of the {} architectural style",
    # "the {} architectural style",
    # "a photo of a {} style building",
    # "a {} style building",
    # "a building in the {} style",
    # "{}-style building",
    # "a {} building",
    # "a building of {} architecture",
    # "a representation of {} architecture",
    # "the facade of a {} building",
    # "an example of {} architecture",
]

CSV_PATH = "benchmark_results_zero_shot.csv"
CSV_PER_CLASS_FOLDER = "./per_class_metrics/"
CONF_MATRIX_FOLDER="./confusoin_matrices/"

device = "cuda:1" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

Using device: cuda:1

In [15]:
if not os.path.isdir(CSV_PER_CLASS_FOLDER):
    os.makedirs(CSV_PER_CLASS_FOLDER)
if not os.path.isdir(CONF_MATRIX_FOLDER):
    os.makedirs(CONF_MATRIX_FOLDER)

assert os.path.isdir(DATASET_PATH), f"DATASET_PATH not found: {DATASET_PATH}"
split_path = os.path.join(DATASET_PATH, SPLIT)
assert os.path.isdir(split_path), f"Split '{SPLIT}' not found in {DATASET_PATH}"




assert os.path.isdir(DATASET_PATH), f"DATASET_PATH not found: {DATASET_PATH}"
split_path = os.path.join(DATASET_PATH, SPLIT)
assert os.path.isdir(split_path), f"Split '{SPLIT}' not found in {DATASET_PATH}"
ds = ImageFolder(split_path)
classnames = ds.classes
num_classes = len(classnames)

print("Number of Classes: ", num_classes)
print("Classes example: ", classnames[:10])


def make_prompts(cname):
    return 

# Make the prompt from the templates prompts
all_prompts, class_offsets = [], [0]
for cname in classnames:
    ps = [t.format(cname) for t in TEMPLATES] + [f"{cname} architecture"]
    all_prompts.extend(ps)
    class_offsets.append(len(all_prompts))

Number of Classes:  25
Classes example:  ['Achaemenid', 'American Foursquare', 'American craftsman', 'Ancient Egyptian', 'Art Deco', 'Art Nouveau', 'Baroque', 'Bauhaus', 'Beaux-Arts', 'Byzantine']

In [16]:
def evaluate(model,
            tokenizer:(open_clip.tokenizer.SimpleTokenizer | open_clip.tokenizer.HFTokenizer | open_clip.tokenizer.SigLipTokenizer),
            dl : DataLoader):

    # Tokenize and encode prompts

    tokens = tokenizer(all_prompts).to(device)

    with torch.no_grad():
        text_features = model.encode_text(tokens)
        text_features = text_features / torch.linalg.norm(text_features,dim=-1, keepdim=True)

    
    y_true, y_pred = [], []
    probs_collector = []
    model_dtype = next(model.parameters()).dtype

    with torch.no_grad():
        for imgs, labels in dl:
            imgs = imgs.to(device, dtype=model_dtype)
            img_features = model.encode_image(imgs)
            img_features = img_features / torch.linalg.norm(img_features,dim=-1, keepdim=True)

            # native logit scale  * custom temperature
            logit_scale = model.logit_scale.exp() #* temp
            logits = logit_scale * (img_features @ text_features.T)

            # class prompt aggregation
            class_logits = []
            for i in range(num_classes):
                s, e = class_offsets[i], class_offsets[i+1]
                class_logits.append(logits[:, s:e].mean(dim=1))
            class_logits = torch.stack(class_logits, dim=1)

            prob = class_logits.softmax(dim=-1)
            pred = prob.argmax(dim=-1)

            y_true.extend(labels.tolist())
            y_pred.extend(pred.tolist())
            probs_collector.append(prob.cpu().numpy())

    y_true = np.array(y_true, dtype=int)
    y_pred = np.array(y_pred, dtype=int)
    probs = np.concatenate(probs_collector, axis=0)

    top1 = accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average="macro")
    top2 = top_k_accuracy_score(y_true, probs, k=min(2, num_classes), labels=np.arange(num_classes))
    top3 = top_k_accuracy_score(y_true, probs, k=min(3, num_classes), labels=np.arange(num_classes))

    return top1, macro_f1, top2, top3, y_true, y_pred, probs

In [17]:
# Latency (ms/img) measured on some batches (with warm up)
def measure_latency(model, dl : DataLoader, num_batches=150, warmup_batches=20):
    model_dtype = next(model.parameters()).dtype
    # warmup
    it = iter(dl)
    for _ in range(warmup_batches):
        try:
            imgs, _ = next(it)
        except StopIteration:
            it = iter(dl)
            imgs, _ = next(it)
        imgs = imgs.to(device, dtype=model_dtype,non_blocking=True)
        with torch.no_grad():
            _ = model.encode_image(imgs)
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    # timed
    times = []
    it = iter(dl)
    for _ in range(num_batches):
        try:
            imgs, _ = next(it)
        except StopIteration:
            it = iter(dl)
            imgs, _ = next(it)
        imgs = imgs.to(device, dtype=model_dtype, non_blocking=True)
        if torch.cuda.is_available():
            torch.cuda.synchronize()  # Ensure transfer is complete
        if torch.cuda.is_available():
            start_event = torch.cuda.Event(enable_timing=True)
            end_event = torch.cuda.Event(enable_timing=True)
            
            start_event.record()
            with torch.no_grad():
                _ = model.encode_image(imgs)
            end_event.record()
            
            torch.cuda.synchronize()
            dt_ms = start_event.elapsed_time(end_event)  # Already in milliseconds
        else:
            t0 = time.perf_counter()  # More precise than time.time()
            with torch.no_grad():
                _ = model.encode_image(imgs)
            dt_ms = (time.perf_counter() - t0) * 1000.0
        
        ms_per_img = dt_ms / imgs.size(0)
        times.append(ms_per_img)
    
    # Return mean and std for better insight
    times = np.array(times)
    return {
        'mean_ms': float(np.mean(times)),
        'std_ms': float(np.std(times)),
#        'median_ms': float(np.median(times)),
#        'min_ms': float(np.min(times)),
#        'max_ms': float(np.max(times))
    }
    #return float(np.mean(times))

In [18]:
def save_to_csv(row:dict):
    df = pd.DataFrame([row])
    display(df)

    # Aggiungi le performance al csv con tutti i modelli
    if os.path.exists(CSV_PATH):
        old = pd.read_csv(CSV_PATH)
        out = pd.concat([old, df], ignore_index=True)
    else:
        out = df.copy()
    out.to_csv(CSV_PATH, index=False)

In [19]:
# saves the per class performance in the file ./<CSV_PER_CLASS_FOLDER>/<model_name>.csv
# also saves the confusion matrix in a file ./<CONF_MATRIX_FOLDER>/<model_name
def save_performance_per_class(y_true,y_pred,model_name:str):
    df=pd.DataFrame(classification_report(y_true, y_pred, target_names=classnames, digits=4 , zero_division=0,output_dict=True))
    df=df.transpose()
    df.columns=["Precision","Recall","F1-score","Support"]
    df.to_csv(os.path.join(CSV_PER_CLASS_FOLDER, model_name+'.csv'), index=True)


    fig, ax = plt.subplots(figsize=(8, 6))
    ConfusionMatrixDisplay.from_predictions(
        y_true, y_pred,
        display_labels=classnames,
        normalize="true",           # percentuali per riga
        cmap="Blues",
        include_values=False,       # evita numeri sopra le celle se hai tante classi
        xticks_rotation=90,
        ax=ax,
        colorbar=True
    )
    
    ax.set_title("Confusion Matrix (normalized)")
    plt.tight_layout()
    plt.savefig(os.path.join(CONF_MATRIX_FOLDER, model_name))
    plt.close()

In [20]:
# make the warning containing "quick_gelu" an exception
# because some openai models need the "force_quick_gelu=True" set
warnings.filterwarnings("error",".*quick_gelu.*",UserWarning)
counter=1
for model_name, pretrained_name in MODELS_LIST:
    torch.manual_seed(SEED)
    np.random.seed(SEED)

    print(f"Model {model_name}, {pretrained_name}  ({counter}/{len(MODELS_LIST)})")
    try:
    
        model, _, preprocess = open_clip.create_model_and_transforms(
            model_name=model_name,
            pretrained=pretrained_name
        )
    
    except UserWarning:
        model, _, preprocess = open_clip.create_model_and_transforms(
            model_name=model_name,
            pretrained=pretrained_name,
            force_quick_gelu=True
        )

    tokenizer = open_clip.get_tokenizer(model_name)
    model.to(device).eval()
    ds.transform=preprocess # type: ignore
    dl = DataLoader(ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=8, pin_memory=True)

    top1, macro_f1, top2, top3, y_true, y_pred, probs=evaluate(model,tokenizer,dl)

    # To measure latency correctly the batch size should be set to 1 (so new DataLoader needed)
    dl = DataLoader(ds, batch_size=1, shuffle=False, num_workers=2, pin_memory=True)
    latency_ms = measure_latency(model,dl,num_batches=min(250, len(ds)),warmup_batches=50)
    
    row = {
        "Timestamp": datetime.now(ZoneInfo("Europe/Rome")).isoformat(),
        "Model": model_name,
        "Pretrained": pretrained_name,
        "Scenario": f"Zero-shot ({SPLIT})",
        "Techniques": f"Prompt ensemble({len(TEMPLATES)} prompts)",
        "Top-1 Acc": round(float(top1), 4),
        "Top-2 Acc": round(float(top2), 4),
        "Top-3 Acc": round(float(top3), 4),
        "Macro-F1": round(float(macro_f1), 4),
        "Latency (ms/img)": f"{latency_ms['mean_ms']:.2f} ± {latency_ms['std_ms']:.2f} ms",
        "Classes": int(len(classnames)),
        "Batch size": int(BATCH_SIZE)
    }
    save_to_csv(row)
    save_performance_per_class(y_true,y_pred,model_name)
    del model
    del tokenizer
    del dl
    torch.cuda.empty_cache()
    gc.collect()
    counter+=1

Model RN50, openai  (1/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:10:07.055431+01:00,RN50,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.4789,0.6402,0.7428,0.4389,4.49 ± 0.65 ms,25,64

Model RN101, openai  (2/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:10:28.630445+01:00,RN101,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.4655,0.6528,0.7465,0.4345,8.57 ± 0.94 ms,25,64

Model RN50x64, openai  (3/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:14:13.911574+01:00,RN50x64,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.5768,0.7473,0.817,0.559,38.23 ± 3.39 ms,25,64

Model ViT-B-32, openai  (4/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:14:32.469321+01:00,ViT-B-32,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.5134,0.6797,0.7895,0.4846,3.88 ± 0.52 ms,25,64

Model ViT-B-16, openai  (5/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:15:02.000588+01:00,ViT-B-16,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.5001,0.6625,0.7611,0.4773,3.95 ± 0.66 ms,25,64

Model ViT-L-14, openai  (6/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:16:49.518942+01:00,ViT-L-14,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.5483,0.6986,0.782,0.5337,17.43 ± 2.88 ms,25,64

Model ViT-L-14-336, openai  (7/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:21:00.963905+01:00,ViT-L-14-336,openai,Zero-shot (train),Prompt ensemble(1 prompts),0.5686,0.7133,0.7884,0.5526,36.13 ± 4.86 ms,25,64

Model ViT-B-32, laion2b_s34b_b79k  (8/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:21:19.496125+01:00,ViT-B-32,laion2b_s34b_b79k,Zero-shot (train),Prompt ensemble(1 prompts),0.5433,0.699,0.7891,0.5035,3.56 ± 0.61 ms,25,64

Model ViT-B-16, laion2b_s34b_b88k  (9/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:21:47.763174+01:00,ViT-B-16,laion2b_s34b_b88k,Zero-shot (train),Prompt ensemble(1 prompts),0.5326,0.7172,0.8143,0.4946,3.69 ± 0.69 ms,25,64

Model ViT-L-14, laion2b_s32b_b82k  (10/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:23:35.864665+01:00,ViT-L-14,laion2b_s32b_b82k,Zero-shot (train),Prompt ensemble(1 prompts),0.6119,0.7752,0.8501,0.5771,17.07 ± 2.97 ms,25,64

Model ViT-H-14, laion2b_s32b_b79k  (11/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:27:03.269666+01:00,ViT-H-14,laion2b_s32b_b79k,Zero-shot (train),Prompt ensemble(1 prompts),0.6215,0.7902,0.8662,0.5919,35.35 ± 4.66 ms,25,64

Model ViT-g-14, laion2b_s12b_b42k  (12/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:32:24.176172+01:00,ViT-g-14,laion2b_s12b_b42k,Zero-shot (train),Prompt ensemble(1 prompts),0.6131,0.7618,0.8436,0.5906,55.23 ± 5.85 ms,25,64

Model ViT-bigG-14, laion2b_s39b_b160k  (13/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:41:49.559216+01:00,ViT-bigG-14,laion2b_s39b_b160k,Zero-shot (train),Prompt ensemble(1 prompts),0.6457,0.7856,0.8623,0.6162,94.79 ± 8.01 ms,25,64

Model ViT-B-32, datacomp_xl_s13b_b90k  (14/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:42:08.541061+01:00,ViT-B-32,datacomp_xl_s13b_b90k,Zero-shot (train),Prompt ensemble(1 prompts),0.564,0.7155,0.7925,0.5312,3.61 ± 0.60 ms,25,64

Model ViT-B-16, datacomp_xl_s13b_b90k  (15/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:42:37.790868+01:00,ViT-B-16,datacomp_xl_s13b_b90k,Zero-shot (train),Prompt ensemble(1 prompts),0.5602,0.7179,0.8046,0.5302,3.67 ± 0.63 ms,25,64

Model ViT-L-14, datacomp_xl_s13b_b90k  (16/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:44:33.283249+01:00,ViT-L-14,datacomp_xl_s13b_b90k,Zero-shot (train),Prompt ensemble(1 prompts),0.6357,0.7741,0.8494,0.6092,17.04 ± 2.90 ms,25,64

Model ViT-H-14, dfn5b  (17/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:48:10.414553+01:00,ViT-H-14,dfn5b,Zero-shot (train),Prompt ensemble(1 prompts),0.658,0.8254,0.8854,0.6423,36.49 ± 4.86 ms,25,64

Model ViT-B-32, metaclip_400m  (18/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:48:29.127415+01:00,ViT-B-32,metaclip_400m,Zero-shot (train),Prompt ensemble(1 prompts),0.5199,0.6917,0.7852,0.505,3.86 ± 0.60 ms,25,64

Model ViT-B-32, metaclip_fullcc  (19/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:48:47.761913+01:00,ViT-B-32,metaclip_fullcc,Zero-shot (train),Prompt ensemble(1 prompts),0.5583,0.7483,0.8341,0.5423,3.86 ± 0.63 ms,25,64

Model ViT-L-14, metaclip_400m  (20/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:50:37.309383+01:00,ViT-L-14,metaclip_400m,Zero-shot (train),Prompt ensemble(1 prompts),0.5521,0.7328,0.8162,0.5359,17.66 ± 2.99 ms,25,64

Model ViT-L-14, metaclip_fullcc  (21/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:52:26.827875+01:00,ViT-L-14,metaclip_fullcc,Zero-shot (train),Prompt ensemble(1 prompts),0.6497,0.8053,0.87,0.6345,17.45 ± 3.04 ms,25,64

Model ViT-H-14, metaclip_fullcc  (22/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T00:56:02.119852+01:00,ViT-H-14,metaclip_fullcc,Zero-shot (train),Prompt ensemble(1 prompts),0.662,0.8169,0.8838,0.6509,36.37 ± 4.57 ms,25,64

Model ViT-bigG-14, metaclip_fullcc  (23/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:05:41.260582+01:00,ViT-bigG-14,metaclip_fullcc,Zero-shot (train),Prompt ensemble(1 prompts),0.6939,0.8322,0.8954,0.6764,96.00 ± 7.00 ms,25,64

Model ViT-B-16-SigLIP, webli  (24/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:06:11.806650+01:00,ViT-B-16-SigLIP,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.479,0.6636,0.7429,0.4642,4.53 ± 0.72 ms,25,64

Model ViT-B-16-SigLIP-256, webli  (25/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:06:48.113623+01:00,ViT-B-16-SigLIP-256,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.4735,0.6595,0.7421,0.4573,4.60 ± 0.69 ms,25,64

Model ViT-B-16-SigLIP-384, webli  (26/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:08:07.843775+01:00,ViT-B-16-SigLIP-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.4895,0.6691,0.7529,0.4701,10.82 ± 2.12 ms,25,64

Model ViT-B-16-SigLIP-512, webli  (27/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:10:42.111999+01:00,ViT-B-16-SigLIP-512,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5049,0.6826,0.7563,0.4873,21.50 ± 4.07 ms,25,64

Model ViT-L-16-SigLIP-256, webli  (28/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:12:25.482569+01:00,ViT-L-16-SigLIP-256,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5529,0.7144,0.7949,0.5436,15.73 ± 2.72 ms,25,64

Model ViT-L-16-SigLIP-384, webli  (29/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:16:22.487829+01:00,ViT-L-16-SigLIP-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5773,0.7255,0.8004,0.5624,34.89 ± 4.93 ms,25,64

Model ViT-SO400M-14-SigLIP-384, webli  (30/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:23:41.987090+01:00,ViT-SO400M-14-SigLIP-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.7139,0.8462,0.9036,0.6921,60.77 ± 6.58 ms,25,64

Model ViT-SO400M-14-SigLIP-378, webli  (31/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:31:00.688383+01:00,ViT-SO400M-14-SigLIP-378,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.7149,0.8479,0.9025,0.6926,60.32 ± 6.58 ms,25,64

Model ViT-B-16-SigLIP2, webli  (32/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:31:33.130108+01:00,ViT-B-16-SigLIP2,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5758,0.7545,0.8422,0.5627,4.41 ± 0.69 ms,25,64

Model ViT-B-16-SigLIP2-256, webli  (33/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:32:11.517526+01:00,ViT-B-16-SigLIP2-256,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5897,0.7665,0.8516,0.5728,4.52 ± 0.70 ms,25,64

Model ViT-B-16-SigLIP2-384, webli  (34/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:33:33.712847+01:00,ViT-B-16-SigLIP2-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5825,0.7538,0.8418,0.5661,10.86 ± 2.20 ms,25,64

Model ViT-B-16-SigLIP2-512, webli  (35/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:36:09.542467+01:00,ViT-B-16-SigLIP2-512,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.5869,0.7568,0.841,0.5689,21.63 ± 3.90 ms,25,64

Model ViT-L-16-SigLIP2-256, webli  (36/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:37:55.110814+01:00,ViT-L-16-SigLIP2-256,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6566,0.8085,0.8711,0.6431,15.70 ± 2.63 ms,25,64

Model ViT-L-16-SigLIP2-384, webli  (37/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:43:35.405589+01:00,ViT-L-16-SigLIP2-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6562,0.8057,0.8714,0.6451,63.04 ± 9.63 ms,25,64

Model ViT-L-16-SigLIP2-512, webli  (38/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T01:57:20.918139+01:00,ViT-L-16-SigLIP2-512,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.67,0.8159,0.8777,0.6548,115.63 ± 13.09 ms,25,64

Model ViT-SO400M-14-SigLIP2, webli  (39/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T02:01:40.141626+01:00,ViT-SO400M-14-SigLIP2,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6713,0.8268,0.8915,0.6525,33.20 ± 7.05 ms,25,64

Model ViT-SO400M-14-SigLIP2-378, webli  (40/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T02:13:41.386040+01:00,ViT-SO400M-14-SigLIP2-378,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6671,0.8214,0.8879,0.6502,94.94 ± 10.05 ms,25,64

Model ViT-SO400M-16-SigLIP2-384, webli  (41/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T02:23:00.413213+01:00,ViT-SO400M-16-SigLIP2-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6712,0.8222,0.8907,0.6533,77.38 ± 9.26 ms,25,64

Model ViT-SO400M-16-SigLIP2-512, webli  (42/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T02:40:49.646550+01:00,ViT-SO400M-16-SigLIP2-512,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6797,0.826,0.893,0.661,145.72 ± 14.53 ms,25,64

Model ViT-gopt-16-SigLIP2-384, webli  (43/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T03:04:39.332514+01:00,ViT-gopt-16-SigLIP2-384,webli,Zero-shot (train),Prompt ensemble(1 prompts),0.6891,0.8346,0.8956,0.6833,206.77 ± 16.78 ms,25,64

Model EVA01-g-14, laion400m_s11b_b41k  (44/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T03:13:28.454349+01:00,EVA01-g-14,laion400m_s11b_b41k,Zero-shot (train),Prompt ensemble(1 prompts),0.5465,0.7333,0.8302,0.5265,95.11 ± 8.39 ms,25,64

Model EVA02-B-16, merged2b_s8b_b131k  (45/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T03:14:20.568281+01:00,EVA02-B-16,merged2b_s8b_b131k,Zero-shot (train),Prompt ensemble(1 prompts),0.5039,0.677,0.7855,0.4954,7.82 ± 0.63 ms,25,64

Model EVA02-L-14, merged2b_s4b_b131k  (46/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T03:17:51.546152+01:00,EVA02-L-14,merged2b_s4b_b131k,Zero-shot (train),Prompt ensemble(1 prompts),0.5977,0.7721,0.8578,0.5852,33.06 ± 6.37 ms,25,64

Model EVA02-L-14-336, merged2b_s6b_b61k  (47/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T03:25:57.209172+01:00,EVA02-L-14-336,merged2b_s6b_b61k,Zero-shot (train),Prompt ensemble(1 prompts),0.6082,0.7792,0.8636,0.5957,69.31 ± 8.20 ms,25,64

Model EVA02-E-14, laion2b_s4b_b115k  (48/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:03:57.783283+01:00,EVA02-E-14,laion2b_s4b_b115k,Zero-shot (train),Prompt ensemble(1 prompts),0.6277,0.7955,0.8696,0.5938,410.71 ± 25.57 ms,25,64

Model EVA02-E-14-plus, laion2b_s9b_b144k  (49/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:41:49.444298+01:00,EVA02-E-14-plus,laion2b_s9b_b144k,Zero-shot (train),Prompt ensemble(1 prompts),0.6488,0.7935,0.8662,0.619,408.63 ± 25.08 ms,25,64

Model convnext_base, laion400m_s13b_b51k  (50/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:42:39.469004+01:00,convnext_base,laion400m_s13b_b51k,Zero-shot (train),Prompt ensemble(1 prompts),0.505,0.6612,0.7515,0.4622,7.46 ± 1.40 ms,25,64

Model convnext_base_w, laion2b_s13b_b82k  (51/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:43:41.225535+01:00,convnext_base_w,laion2b_s13b_b82k,Zero-shot (train),Prompt ensemble(1 prompts),0.551,0.723,0.8088,0.5064,7.53 ± 1.43 ms,25,64

Model convnext_large_d, laion2b_s26b_b102k_augreg  (52/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:45:41.691842+01:00,convnext_large_d,laion2b_s26b_b102k_augreg,Zero-shot (train),Prompt ensemble(1 prompts),0.5739,0.7522,0.8444,0.5576,15.46 ± 4.07 ms,25,64

Model convnext_large_d_320, laion2b_s29b_b131k_ft_soup  (53/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:48:39.131046+01:00,convnext_large_d_320,laion2b_s29b_b131k_ft_soup,Zero-shot (train),Prompt ensemble(1 prompts),0.5787,0.7527,0.841,0.5635,27.18 ± 6.85 ms,25,64

Model convnext_xxlarge, laion2b_s34b_b82k_augreg  (54/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:55:51.625351+01:00,convnext_xxlarge,laion2b_s34b_b82k_augreg,Zero-shot (train),Prompt ensemble(1 prompts),0.6404,0.7918,0.8615,0.6116,64.48 ± 9.87 ms,25,64

Model coca_ViT-B-32, laion2b_s13b_b90k  (55/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:56:12.646447+01:00,coca_ViT-B-32,laion2b_s13b_b90k,Zero-shot (train),Prompt ensemble(1 prompts),0.5076,0.6894,0.786,0.4809,3.65 ± 0.55 ms,25,64

Model coca_ViT-L-14, laion2b_s13b_b90k  (56/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T04:59:30.935255+01:00,coca_ViT-L-14,laion2b_s13b_b90k,Zero-shot (train),Prompt ensemble(1 prompts),0.6,0.7486,0.8253,0.5642,29.87 ± 7.58 ms,25,64

Model ViT-L-14-CLIPA, datacomp1b  (57/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:02:44.093133+01:00,ViT-L-14-CLIPA,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6183,0.7808,0.8598,0.6048,29.51 ± 7.35 ms,25,64

Model ViT-L-14-CLIPA-336, datacomp1b  (58/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:10:15.914823+01:00,ViT-L-14-CLIPA-336,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6277,0.787,0.8642,0.6079,63.86 ± 10.45 ms,25,64

Model ViT-H-14-CLIPA, datacomp1b  (59/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:16:24.717613+01:00,ViT-H-14-CLIPA,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6606,0.8121,0.8739,0.6363,62.16 ± 9.78 ms,25,64

Model ViT-H-14-CLIPA-336, datacomp1b  (60/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:29:49.107929+01:00,ViT-H-14-CLIPA-336,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.665,0.8194,0.8867,0.643,113.68 ± 11.92 ms,25,64

Model ViT-bigG-14-CLIPA, datacomp1b  (61/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:46:44.778448+01:00,ViT-bigG-14-CLIPA,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6602,0.7997,0.8682,0.6434,175.34 ± 15.98 ms,25,64

Model ViTamin-L, datacomp1b  (62/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:49:57.537983+01:00,ViTamin-L,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6351,0.7724,0.8527,0.6118,31.09 ± 6.71 ms,25,64

Model ViTamin-L-336, datacomp1b  (63/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T05:57:08.549669+01:00,ViTamin-L-336,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6364,0.776,0.8539,0.6114,57.39 ± 8.29 ms,25,64

Model ViTamin-L2, datacomp1b  (64/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:00:21.770792+01:00,ViTamin-L2,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6572,0.8045,0.8699,0.6352,31.23 ± 6.75 ms,25,64

Model ViTamin-L2-384, datacomp1b  (65/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:09:58.677291+01:00,ViTamin-L2-384,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6517,0.8045,0.8698,0.6316,74.66 ± 7.83 ms,25,64

Model ViTamin-XL-336, datacomp1b  (66/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:18:50.549007+01:00,ViTamin-XL-336,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6497,0.784,0.8652,0.6292,74.26 ± 7.88 ms,25,64

Model ViTamin-XL-384, datacomp1b  (67/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:23:59.636768+01:00,ViTamin-XL-384,datacomp1b,Zero-shot (train),Prompt ensemble(1 prompts),0.6431,0.7847,0.8579,0.6197,38.37 ± 7.21 ms,25,64

Model PE-Core-B-16, meta  (68/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:24:55.169310+01:00,PE-Core-B-16,meta,Zero-shot (train),Prompt ensemble(1 prompts),0.6127,0.7873,0.8731,0.595,7.13 ± 1.37 ms,25,64

Model PE-Core-L-14-336, meta  (69/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T06:33:02.084564+01:00,PE-Core-L-14-336,meta,Zero-shot (train),Prompt ensemble(1 prompts),0.6519,0.8184,0.89,0.6376,67.48 ± 9.02 ms,25,64

Model PE-Core-bigG-14-448, meta  (70/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T07:44:28.803294+01:00,PE-Core-bigG-14-448,meta,Zero-shot (train),Prompt ensemble(1 prompts),0.6826,0.825,0.8936,0.6805,541.39 ± 28.25 ms,25,64

Model ViT-H-14-worldwide-378, metaclip2_worldwide  (71/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T08:02:17.819477+01:00,ViT-H-14-worldwide-378,metaclip2_worldwide,Zero-shot (train),Prompt ensemble(1 prompts),0.6435,0.7931,0.8604,0.6284,151.42 ± 15.90 ms,25,64

Model ViT-bigG-14-worldwide, metaclip2_worldwide  (72/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T08:19:29.675750+01:00,ViT-bigG-14-worldwide,metaclip2_worldwide,Zero-shot (train),Prompt ensemble(1 prompts),0.7015,0.8517,0.9108,0.6871,176.93 ± 15.78 ms,25,64

Model ViT-bigG-14-worldwide-378, metaclip2_worldwide  (73/73)

,Timestamp,Model,Pretrained,Scenario,Techniques,Top-1 Acc,Top-2 Acc,Top-3 Acc,Macro-F1,Latency (ms/img),Classes,Batch size
0,2025-10-28T09:08:00.417933+01:00,ViT-bigG-14-worldwide-378,metaclip2_worldwide,Zero-shot (train),Prompt ensemble(1 prompts),0.6905,0.8466,0.9067,0.6788,387.53 ± 30.34 ms,25,64